### ISSUE TITLE
Scala 2.11 support

### ISSUE THREAD

**Issue by Tooa** [gangeli/sim#1]
Hi :wave:,

any chance to get the serialized models for Scala 2.11? At the moment Scala 2.11 throws the following error:

```bash
scala> implicit val wordnet = Ontology.load("etc/ontology.ser.gz")
java.io.InvalidClassException: scala.collection.immutable.$colon$colon; local class incompatible: stream classdesc serialVersionUID = -8476791151983527571, local class serialVersionUID = 509929039250432923
  at java.io.ObjectStreamClass.initNonProxy(ObjectStreamClass.java:621)
  at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1623)
  at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1518)
  at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1774)
  at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
  at java.io.ObjectInputStream.readObject(ObjectInputStream.java:371)
  at scala.collection.immutable.HashMap$SerializationProxy.readObject(HashMap.scala:582)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:483)
  at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1017)
  at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1896)
  at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1801)
  at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
  at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1993)
  at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1918)
  at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1801)
  at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1351)
  at java.io.ObjectInputStream.readObject(ObjectInputStream.java:371)
  at org.goobs.sim.Util$.readObject(Util.scala:110)
  at org.goobs.sim.Ontology$.load(Ontology.scala:587)
  ... 33 elided
```

**Comment by Tooa** [comment]
After some more digging, I found the `mk_\*` scripts in `/etc`. 

Why is the path similarity negative? The example in the `README.md` yields `-1.3862943611198906`. The score in [NLTK](http://www.nltk.org/howto/wordnet.html) is between [0,1]. What does the negative score mean? Log values?
